### ISSUE TITLE
Carthage compatibility?

### ISSUE THREAD

**Issue by broomburgo** [typelift/Operadics#13]
Is there a particular reason why this library is not compatible with Carthage? The way Operadics is wired in other libraries (e.g. in [Abstract](https://github.com/typelift/Abstract/issues/23)), and the requirement of a manual build even for nested dependencies seems too cumbersome.

**Comment by bkase** [comment]
This was a hack I did to get it to support Swift Package Manager -- at the time I couldn't come up with a way to make both work without the extra command in Carthage. It would be *awesome* if you know of a way to get around it. I totally agree with you!

**Comment by CodaFi** [comment]
> Is there a particular reason why this library is not compatible with Carthage?

No particular reason, just never needed to support it and nobody before you has asked for it.

> The requirement of a manual build even for nested dependencies seems too cumbersome.

Sure.  I'd certainly take the cartfile, but it would also mean that if Abstract consumed it that it'd be the only library of ours that uses Carthage as a primary build system.

**Comment by broomburgo** [comment]
I see Carthage compatibility as a purely additive feature, designed to make these libraries work out-of-the-box in a iOS development context. I'm using Abstract (thus, Operadics) at large in my daily work, both the library itself and other libraries I wrote that use it, and I can tell that making it fully compatible with Carthage (or CocoaPods, but I don't use it and I don't care about it) is basically needed to avoid alienating potential users. The reason why I asked "is there a particular reason" is that in "modern" modular iOS development I consider Carthage support as a given.

> if Abstract consumed it that it'd be the only library of ours that uses Carthage as a primary build system

That's mostly due to the sad state of dependency management in Swift development: the most relevant area for Swift developers is iOS by far, but it's not compatible yet with the Swift package manager. I'd personally favor an approach that makes iOS/macOS development easier, with workarounds for other platforms, than the other way around.

Still, I think we can leave the things as they are but clearly document in the READMEs what has to be done if you want to use Operadics or libraries that depend on it. For example, in one of my libraries I suggest (in the README) to let `carthage update` fail and then launch [this](https://github.com/broomburgo/Monads/blob/master/buildOperadics.sh) script.

I'm going to prepare a pr for Abstract in which I rewrite the README, and if things stay as they are, I'm going to add the script to build Operadics and add a line in the README for it.
