### ISSUE TITLE
Pipe operator associativity

### ISSUE THREAD

**Issue by mpurland** [typelift/Operadics#3]
``` swift
/// Pipe Backward | Applies the function to its left to an argument on its right.
infix operator <| {
    associativity right
    precedence 95
}

/// Pipe forward | Applies an argument on the left to a function on the right.
infix operator |> {
    associativity left
    precedence 95
}
```

In Swiftz/Operadics <| is associativity right, and |> is associativity left. Should this not be reversed?

Proposed change:

``` swift

/// Pipe Backward | Applies the function to its left to an argument on its right.
infix operator <| {
    associativity left
    precedence 95
}

/// Pipe forward | Applies an argument on the left to a function on the right.
infix operator |> {
    associativity right
    precedence 95
}
```

This would also match Argo's implementation: https://github.com/thoughtbot/Argo/blob/master/Argo/Operators/Argo.swift

This change would allow pipe chaining, unless |> is the intended behavior?

**Comment by CodaFi** [comment]
I believe Argo has this wrong.

[Elm](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Basics#<|), [Haskell](http://hackage.haskell.org/package/base-4.8.1.0/docs/Prelude.html#v:-36-), [ML](http://mlton.org/InfixingOperators), and IIRC Scalaz all agree with us.

**Comment by CodaFi** [comment]
They appear to be using `<|` for things other than function application too for some reason.

**Comment by mpurland** [comment]
That's what I thought. I verified with F# also.

In order to implement chaining then pipe forward |> should be used since the function will be on the left. What about this?

``` swift
public func |> <A, B>(f : (A? -> B)?, a : A?) -> B? {
    return f?(a)
}
```

To handle the case for an input function (A? -> B)?

**Comment by CodaFi** [comment]
Now that's a strange function (It looks useful, tho!).  Here you're confusing something comonadic-like with an actual function.  That is not a function on the left, that's a value that could be a function.

**Comment by mpurland** [comment]
How would you go about this given the following example:

``` swift
struct Object {
    let required1: String
    let required2: String
    let optional1: String?
    let optional2: String?
}

extension Object: JSONDecodable {
    static func fromJSON(x : JSONValue) -> Object? {
        let p1: String? = x <? "required1"
        let p2: String? = x <? "required2"
        let p3: String? = x <? "optional1"
        let p4: String? = x <? "optional2"

        return curry(Object.init) <^> p1 <*> p2 <*> p3 <*> p4
    }
}
```

In this case, if `p3` and `p4` are nil then the Object will not be constructed even though the parameters are optional. How would you allow the object to be constructed in this case even if p3 and p4 are .None?

**Comment by CodaFi** [comment]
We have no such concept of "required" and "not" parameters when it comes to JSON.  Either they're there or they're not (which is what the chain of Applicative operators is saying).

**Comment by CodaFi** [comment]
If you want the parameters (and hence, the whole object) to stick around, use `??` to provide a default value in case of failure.

**Comment by mpurland** [comment]
Consider this case, the last two parameters are booleans instead. 

``` swift
struct Object {
    let required1: String
    let required2: String
    let optional1: Bool?
    let optional2: Bool?
}

extension Object: JSONDecodable {
    static func fromJSON(x : JSONValue) -> Object? {
        let p1: String? = x <? "required1"
        let p2: String? = x <? "required2"
        let p3: String? = x <? "optional1"
        let p4: String? = x <? "optional2"

        return curry(Object.init) <^> p1 <*> p2 <*> p3 <*> p4
    }
}
```

There is a difference between optional1/optional2 with default values of false (for example). The possible states for this are .None, .Some(false), and .Some(true). However, you may have business logic that depends on the property being not specified (optional) rather than false. 

This is possible, but not very nice and only works this way because the two optional parameters are at the end of the curried functions parameter list.

``` swift
return (curry(Object.init) <^> p1 <*> p2)?(p3)(p4)
```

**Comment by CodaFi** [comment]
Then the proper type of `p3` and `p4` is not `Optional<String>`, it's `Optional<Optional<String>>`.  Compose with `Optional.Some` and it should work.

**Comment by mpurland** [comment]
I'll give that a shot. Similarly, Argo seems to have done it this way as well.

``` swift
// Pull optional value from JSON
public func <|? <T where T: Decodable, T == T.DecodedType>(json: JSON, key: String) -> T?? {
  return json <| [key]
}
```

https://github.com/thoughtbot/Argo/blob/master/Argo/Operators/DecodeOptional.swift

**Comment by CodaFi** [comment]
I'd be open to having a `<??` operator in this library for that purpose (or does a JSON instance of Optional<T> where T : JSON work?)

**Comment by mpurland** [comment]
<?? would make sense in the realm of the JSON serializer for Swiftz. I can try it and draw up a PR if you like.

**Comment by CodaFi** [comment]
Sure.  Let's see what happens.
